"""create observatory schema

Revision ID: d20ee2723bbf
Revises: 
Create Date: 2026-08-14 19:48:14.882594
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'd20ee2723bbf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('news_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('group_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_url')
    )
    op.create_index(op.f('ix_news_items_group_key'), 'news_items', ['group_key'], unique=False)
    op.create_index(op.f('ix_news_items_published_at'), 'news_items', ['published_at'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_symbol', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=32), nullable=False),
    sa.Column('exchange', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_symbol', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_symbol', 'exchange', name='uq_security_identity')
    )
    op.create_index(op.f('ix_securities_canonical_symbol'), 'securities', ['canonical_symbol'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_runs_job_name'), 'sync_runs', ['job_name'], unique=False)
    op.create_table('user_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', name='uq_user_list_kind')
    )
    op.create_table('list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['user_lists.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'security_id', name='uq_list_security')
    )
    op.create_index(op.f('ix_list_items_list_id'), 'list_items', ['list_id'], unique=False)
    op.create_index(op.f('ix_list_items_security_id'), 'list_items', ['security_id'], unique=False)
    op.create_table('news_security_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('relevance', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('news_id', 'security_id', name='uq_news_security')
    )
    op.create_index(op.f('ix_news_security_links_news_id'), 'news_security_links', ['news_id'], unique=False)
    op.create_index(op.f('ix_news_security_links_security_id'), 'news_security_links', ['security_id'], unique=False)
    op.create_table('price_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=True),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'observed_at', 'source', name='uq_price_observation')
    )
    op.create_index(op.f('ix_price_observations_observed_at'), 'price_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_price_observations_security_id'), 'price_observations', ['security_id'], unique=False)
    op.create_index(op.f('ix_price_observations_session_date'), 'price_observations', ['session_date'], unique=False)
    op.create_table('holding_annotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_item_id', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('average_cost', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('cost_currency', sa.String(length=8), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['list_item_id'], ['list_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('holding_annotations')
    op.drop_index(op.f('ix_price_observations_session_date'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_security_id'), table_name='price_observations')
    op.drop_index(op.f('ix_price_observations_observed_at'), table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index(op.f('ix_news_security_links_security_id'), table_name='news_security_links')
    op.drop_index(op.f('ix_news_security_links_news_id'), table_name='news_security_links')
    op.drop_table('news_security_links')
    op.drop_index(op.f('ix_list_items_security_id'), table_name='list_items')
    op.drop_index(op.f('ix_list_items_list_id'), table_name='list_items')
    op.drop_table('list_items')
    op.drop_table('user_lists')
    op.drop_index(op.f('ix_sync_runs_job_name'), table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index(op.f('ix_securities_canonical_symbol'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_news_items_published_at'), table_name='news_items')
    op.drop_index(op.f('ix_news_items_group_key'), table_name='news_items')
    op.drop_table('news_items')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
